### ISSUE TITLE
Update UTILITIES - LOST APPLYMN: Name of script and functionality

### ISSUE THREAD

**Issue by MiKaylaH22** [Hennepin-County/MAXIS-scripts#628] opened 2021-10-12 16:58 UTC
Replace name and update documentation to ensure to support MNbenefits vs, ApplyMN applications, and additional support functionality/updates.  Name of the script will now be APPLICATION INQUIRY.

Functionality
- [x] Add CASE ASSIGMENT navigation button on SPO. 
- [x] Auto-filling date of online application will need to be updated (pulling in date inconsistently)
- [x] Replacement of ApplyMN to MNbenefits

For the Name Change
- [x]  locally-installed-files/redirect-utilities-request-lost-applymn.vbs - name change
- [x] utilities - lost applymn - name change
- [x] Update power pads (general and specialty)
- [x] /COMPLETE LIST OF SCRIPTS.vbs
- [x] Power Pad button name update in SCRIPTS FOR SUPPORT section
- [x] Changelog announcement in FuncLib

**Comment by C-Love** [comment] 2021-10-14 19:49
Need process steps in writing and in the HSR manual.

**Comment by IlseFerris** [comment] 2021-10-15 20:27
Confirmed process for MNBenefits and ApplyMN is the same. Putting this in On Deck status. This will be a great help to CA team. 
Will also need to update the power pad button name in the 'scripts for support' section.

**Comment by IlseFerris** [comment] 2022-03-08 17:04
Name will be updated to APPLICATION INQUIRY

**Comment by IlseFerris** [comment] 2022-03-10 20:35
Adding button to CASE ASSIGNMENT SharePoint Page.

**Comment by IlseFerris** [comment] 2022-04-11 17:44
Aside from the unintended updating of the power pad to remove tags & favorites (which has been resolved, thank you @C-Love, no issues have been reported. Closing issue.

**Closed by IlseFerris** 2022-04-11 17:44 UTC
Labels: Type: Enhancement, Category: UTILITIES, Jar: Sand
