### ISSUE TITLE
BUG Access to SMI - assess the button 

### ISSUE THREAD

**Issue by MiKaylaH22** [Hennepin-County/MAXIS-scripts#502] opened 2021-06-17 18:01 UTC
Bad Request
The request could not be understood by server due to malformed syntax.
https://smi.dhs.state.mn.us/login.do

**Comment by C-Love** [comment] 2021-06-17 18:03
This is not a bug, or a script.

**Comment by C-Love** [comment] 2021-06-17 18:06
The SMI link opens in Edge and recently Edge is not allowing access to the SMI link. If you have IE or Chrome as the default browser, the link is fine. This also used to work in Edge. This will be a problem for us entirly independent of scripts and DHS/IT needs to resolve this.

**Comment by IlseFerris** [comment] 2021-06-25 13:31
Closing issue. Staff have been directed to open in IE.

**Closed by IlseFerris** 2021-06-25 13:31 UTC
Labels: CRITICAL
