### ISSUE TITLE
Expedited SNAP with SPON requires FIAT

### ISSUE THREAD

**Issue by C-Love** [Hennepin-County/MAXIS-scripts#173] opened 2020-08-20 16:22 UTC
Maybe we make a fiater?

**Comment by IlseFerris** [comment] 2020-08-20 21:08
MAXIS Help Desk provided a process to ensure that the case will auto-close correctly due to postponed verification(s). Will be sending a PQ to get the process in writing. Casey is checking with Mandora to see if we have a pending PQ for this issue on 08/20/2020.

**Comment by IlseFerris** [comment] 2021-04-01 20:33
Duplicate of #208

**Closed by IlseFerris** 2021-04-01 20:33 UTC
Labels: Type: Duplicate
