### ISSUE TITLE
AVS Request for QI - handling for no SSN 

### ISSUE THREAD

**Issue by MiKaylaH22** [Hennepin-County/MAXIS-scripts#323] opened 2021-01-14 21:04 UTC
I have forwarded this as M01 is the applicant and has no SSN.  We cannot run an avs.  As such we cannot run and tag M02 as they are not applying.

This is something I think we need to look at for the script, as in this case, this case needs to be handled like it would have been prior to AVS.

**Comment by IlseFerris** [comment] 2021-01-28 18:34
Duplicate of #323. I've updated #323 to include this enhancement.

**Closed by IlseFerris** 2021-01-28 18:34 UTC
Labels: enhancement
