### ISSUE TITLE
Build support for specialty assignment-based DAIL messages

### ISSUE THREAD

**Issue by MiKaylaH22** [Hennepin-County/MAXIS-scripts#235] opened 2020-10-05 20:29 UTC
Filter for the assignments under the DAIL Messages Column 
 Jessica Assignment - "PX, AN, OD"
			60 DAY POST-PARTUM PERIOD HAS ENDED, REVIEW EXTENDED PW ELIG
			 AUTO-NEWBORN ELIG HAS ENDED - REDETERMINE MA ELIG/APPROVE
                         UNBORN CHILD IS OVERDUE

Laurie Assignment - FMED 
MEMBER HAS TURNED 60 - NOTIFY ABOUT POSSIBLE FMED DEDUCTION

**Comment by IlseFerris** [comment] 2020-10-09 22:23
No additional DAIL assignments will be created at this point, but Faughn is very supportive of this process, and the potential for more PEPR's to be added in the future.

**Comment by IlseFerris** [comment] 2020-12-17 21:36
Duplicate of #116. Closing associated issue.

**Comment by IlseFerris** [comment] 2020-12-17 21:58
Several types of DAIL messages are assigned out on a monthly basis. Some of these messages are: PEPR, INFO, some TIKL messages and INAC cases. A holistic approach will need to be created to determine the best course of action. May results in more than one issue/project.

**Comment by IlseFerris** [comment] 2021-02-25 22:41
With the new task based process process coming, QI will no longer be assigned lists of DAIL messages, and other DAIL assignments will become a part of task-based processing in time.

**Closed by IlseFerris** 2021-02-25 22:41 UTC
Labels: BULK, QI, enhancement, wontfix
