### ISSUE TITLE
UTILITIES-NOTICES Fleeing Felon WCOM

### ISSUE THREAD

**Issue by MiKaylaH22** [Hennepin-County/MAXIS-scripts#95] opened 2020-07-01 22:27 UTC
Add   fleeing felon memo script
Kerry Walsh

Give   option to select the programs effected. Temp reference: TE02.08.187. More   than POLI TEMP. Discovery for FPI process.
--

--

**Comment by IlseFerris** [comment] 2021-03-08 18:56
Associated with issue #377

**Comment by IlseFerris** [comment] 2021-05-20 21:06
Duplicate of #377. Closing this issue.

**Closed by IlseFerris** 2021-05-20 21:06 UTC
Labels: Category: NOTICES
