### ISSUE TITLE
NOTES - Application Check - Update to match assignment process and expectations

### ISSUE THREAD

**Issue by C-Love** [Hennepin-County/MAXIS-scripts#803] opened 2022-04-12 15:28 UTC
Application Check was built for the specific process that we used for working cases at application. These expectations and processes have changed and we should review the functionality of this script. 

Ideas to review:
Additional fields for required steps of the process
	- Date field for Date 2919 was actually sent
	- Indicator that PANELS were updated
	- Indicator that DAILs have been reviewewd/removed/acted on
	- Date field for Interview
Special functionality for IMIG
	- SAVE
	- Contact with HP.Immigration
App Type could be removed or pulled from another CASE NOTE - App Received

**Comment by C-Love** [comment] 2022-04-22 17:53
Review HC Process

**Comment by IlseFerris** [comment] 2022-05-19 18:22
For HC applications after PHE ends, do we need to remove the attested verifications support and/or other HC supports?

**Comment by IlseFerris** [comment] 2022-06-15 18:41
Moving to Q3. ES Workflow has just gone live for adults and families. Team will working with Mary D to review this process w/ ES Workflow tool.

**Comment by IlseFerris** [comment] 2022-07-14 19:43
Questions Posed to Project Coordinator:
•	Is CARL still being used? Answer: No
•	What is the criteria/recurrence for ES Workflow to assigning pending cases to staff?
•	Can we repurposed the application check process/script to support the goals of universal task-based processing in ES?

**Comment by IlseFerris** [comment] 2023-04-16 15:02
Enhancements to include using function determine_program_and_case_status_from_CASE_CURR more comprehensively. This script relies on a lot of determination for pending programs that is now handled in this function.

**Comment by IlseFerris** [comment] 2024-05-23 14:59
After much review and spot checking, this tool is not being used as intended. It also does not follow the current ES Workflow Assignment process as it was built for the CARL application. Will be adding a sundown message today, and will retire on 06/03/2024.

**Comment by IlseFerris** [comment] 2024-06-03 16:34
Additional tasks to complete the retirement of this script:
- [ ] Pull instructions down
- [ ] Blank out Hot Topic article calls
- [ ] Update MISC - DESERT ISLAND Menu
- [ ] Move file on T drive to retired
- [ ] Update monthly Desert Island list to remove AC

**Closed** 2024-06-06 19:22 UTC
Labels: Type: Enhancement, Category: NOTES, Agency Planning Needed
